### PR TITLE
Fix newer boost build

### PR DESCRIPTION
**Pull request by trappist**
Got this trying to build on ubuntu 14.04:
```
  CXX      libbitcoin_common_a-chainparams.o
chainparams.cpp: In constructor ‘CMainParams::CMainParams()’:
chainparams.cpp:144:75: error: ambiguous overload for ‘operator=’ (operand types are ‘std::vector<unsigned char>’ and ‘boost::assign_detail::generic_list<unsigned int>’)
         base58Prefixes[EXT_COIN_TYPE]  = boost::assign::list_of(0x80000005);
                                                                           ^
```
This fixes it

### CODE REVIEW

**Comment by spectralsun** [comment]
Please merge this @Truckman83

**Comment by coind0g** [comment]
+1

**Comment by coind0g** [comment]
This has been merged on my fork https://github.com/coind0g/DAS-source
